#!/bin/sh

xsetroot -cursor_name left_ptr &
sxhkd &
#/home/profil/.config/bspwm/panel &

bspc rule -a st-256color:scratchpad sticky=on state=floating

bspc config border_width 2
bspc config window_gap 10
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config auto_cancel true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#bspc config normal_border_color "#262729"
#bspc config focused_border_color "#c6ff55"
#bspc config presel_border_color "#66d9ef"
#bspc config urgent_border_color "#f92672"

bspc monitor -d 1 2 3 4 5 6
