#!/bin/sh

xsetroot -cursor_name left_ptr &
sxhkd &
/home/profil/.config/bspwm/panel &

bspc rule -a scratchpad sticky=on floating=on

bspc config border_width 1
bspc config window_gap 4
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true

bspc config normal_border_color "#323537"
bspc config active_border_color "#838184"
bspc config focused_border_color "#979797"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

bspc monitor -d 1 2 3 4 5 6

